# Porta do servidor
server.port=8085

# Nome da aplicação
spring.application.name=ticketeria-simulador

# Configurações JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=3600000

# Logging
logging.level.com.ticketeria.simulador=DEBUG